### ISSUE TITLE
Implement tbDEX Resource signing & validation

### ISSUE THREAD

**Issue by amika-sq** [TBD54566975/tbdex-rs#16] opened 2023-11-15 15:11 UTC
More info [here](https://github.com/TBD54566975/tbdex/tree/main/specs/protocol#signatures)

**Comment by KendallWeihe** [comment] 2024-04-29 20:45
duplicate of https://github.com/TBD54566975/tbdex-rs/issues/28 and https://github.com/TBD54566975/tbdex-rs/issues/27

**Closed by KendallWeihe** 2024-04-29 20:45 UTC
Labels: tbdex-resource
